/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/todos/{todoId}/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 할일 인증 사진 수정
         * @description 기존 인증 사진을 새 사진으로 수정
         */
        put: operations["updateVerification"];
        /**
         * 할일 인증 사진 업로드
         * @description 할일에 대한 공부 인증 사진을 업로드합니다.
         */
        post: operations["uploadVerification"];
        /**
         * 할일 인증 사진 삭제
         * @description 할일에 등록된 인증 사진을 삭제하고, 할일 상태를 미완료로 변경
         */
        delete: operations["deleteVerification"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentors/weekly-reports/{mentorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 주간 리포트 수정
         * @description 멘토가 등록된 주간 리포트를 수정합니다.
         */
        put: operations["updateWeeklyReport"];
        /**
         * 주간 리포트 생성
         * @description 멘토가 멘티에 대한 주간 리포트를 생성합니다.
         */
        post: operations["createWeeklyReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentors/weakness-solutions/{mentorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 약점 솔루션 수정
         * @description 멘토가 등록된 약점 맞춤 솔루션을 수정합니다.
         */
        put: operations["updateWeaknessSolution"];
        /**
         * 약점 솔루션 생성
         * @description 멘토가 멘티에 대한 약점 맞춤 솔루션을 생성합니다.
         */
        post: operations["createWeaknessSolution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentors/qnas/answer/{userId}/{userRole}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Q&A 답변 등록 (멘토용)
         * @description 멘토가 멘티의 Q&A 질문에 답변을 등록합니다. {userId}와 {userRole}은 인증된 사용자의 ID와 역할입니다.
         */
        put: operations["answerQna"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentees/qnas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Q&A 조회
         * @description 특정 멘티의 특정 날짜 Q&A를 조회합니다.
         */
        get: operations["getQna"];
        /**
         * Q&A 수정
         * @description 멘티가 등록한 Q&A 질문을 수정합니다. 답변이 완료된 Q&A는 수정할 수 없습니다. 다중 파일 업로드를 지원합니다.
         */
        put: operations["updateQna"];
        /**
         * Q&A 질문 등록
         * @description 멘티가 멘토에게 Q&A 질문을 등록합니다. 멘토는 멘티-멘토 관계에서 자동 조회됩니다. 다중 파일 업로드를 지원합니다.
         */
        post: operations["createQna"];
        /**
         * Q&A 삭제
         * @description 멘티가 등록한 Q&A를 삭제합니다.
         */
        delete: operations["deleteQna"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/{assignmentId}/verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 과제 인증 사진 수정
         * @description 기존 인증 사진을 새 사진으로 수정
         */
        put: operations["updateVerification_1"];
        /**
         * 과제 인증 사진 업로드
         * @description 과제에 대한 공부 인증 사진을 업로드합니다. 업로드 시 자동으로 완료 상태로 전환
         */
        post: operations["uploadVerification_1"];
        /**
         * 과제 인증 사진 삭제
         * @description 과제에 등록된 인증 사진을 삭제하고, 과제 상태를 미완료로 변경
         */
        delete: operations["deleteVerification_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 할일 목록 조회
         * @description 전체/기간별/일별 할일 목록을 조회합니다. startDate만 있으면 일별, startDate+endDate는 기간별, 둘 다 없으면 전체 조회
         */
        get: operations["getTodos"];
        put?: never;
        /**
         * 할일 등록
         * @description 새로운 할일을 등록합니다. 과목(subject)은 KOREAN, ENGLISH, MATH 중 하나여야 합니다.
         */
        post: operations["createTodo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todos/{todoId}/timer/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 할일 타이머 세션 추가
         * @description Todo에 타이머 세션(시작~종료)을 추가로 저장합니다.
         */
        post: operations["addTimerSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todos/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 할일 임시 저장 목록 조회
         * @description 임시 저장된 할일 목록을 조회합니다.
         */
        get: operations["getDraftTodos"];
        put?: never;
        /**
         * 할일 임시 저장
         * @description 할일을 임시 저장합니다. 과목(subject)은 KOREAN, ENGLISH, MATH 중 하나여야 합니다.
         */
        post: operations["createDraftTodo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentors/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 과제 생성 및 임시저장
         * @description 멘토가 멘티에게 과제를 배정합니다. 다수의 날짜를 지정할 수 있으며, 학습지 파일을 업로드할 수 있습니다. isDraft 필드로 임시저장 여부를 결정합니다.
         */
        post: operations["createAssignment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/member/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 로그인 API
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedbacks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 피드백 저장 및 수정
         * @description 피드백을 생성하거나 수정합니다. 임시저장(draftYn='Y')과 완료(completeYn='Y')를 구분합니다.
         */
        post: operations["saveFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedbacks/analyze/{todoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * [백그라운드] AI Vision 분석 트리거
         * @description 할 일의 이미지를 분석하여 피드백 초안을 백그라운드에서 생성합니다.
         */
        post: operations["triggerImageAnalysis"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todos/{todoId}/completed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 할일 완료 상태 변경
         * @description 할일의 완료 상태를 토글합니다.
         */
        patch: operations["toggleStatus"];
        trace?: never;
    };
    "/api/todos/{todoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 할일 상세 조회
         * @description 할일 ID를 기반으로 상세 정보를 조회합니다.
         */
        get: operations["getTodoDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todos/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 주차별 할일 목록 조회
         * @description 특정 주차의 월요일 날짜를 기준으로 해당 주(월~일)의 할일 목록을 조회
         */
        get: operations["getTodosWeekly"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todos/timers/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 일별 타이머 조회
         * @description 특정 날짜의 모든 todo_timer를 모아 총시간/평균시간과 함께 반환합니다.
         */
        get: operations["getTimersByDate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todos/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 학습지/파일 다운로드
         * @description 제공된 파일 URL을 통해 파일을 다운로드
         */
        get: operations["downloadFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 알림 목록 조회
         * @description 특정 멘티의 알림 목록을 조회합니다.
         */
        get: operations["getNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentors/{mentorId}/mentees/{menteeId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 멘티별 진행률 통계 조회
         * @description 멘토 ID와 멘티 ID 기반으로 멘티의 전체 및 과목별 과제 진행률을 조회합니다.
         */
        get: operations["getMenteeProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentors/{mentorId}/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 멘토 홈 화면 데이터 조회
         * @description 멘토 ID와 날짜 기반으로 과제, 피드백, Q&A 현황을 조회합니다.
         */
        get: operations["getMentorHomeData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentors/{mentorId}/draft-counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 멘토의 임시저장 개수 조회
         * @description 멘토가 관리하는 멘티들의 과제 및 피드백 임시저장 개수를 조회합니다.
         */
        get: operations["getDraftCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentors/weekly-reports/{reportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 주간 리포트 상세 조회
         * @description 특정 주간 리포트의 상세 정보를 조회합니다.
         */
        get: operations["getWeeklyReportDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentors/weekly-reports/by-mentor/{mentorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 멘토가 관리하는 모든 멘티의 주간 리포트 목록 조회
         * @description 특정 주차(월요일 기준)의 모든 멘티 리포트를 조회합니다. 작성 전인 경우 AI 초안이 포함됩니다.
         */
        get: operations["getWeeklyReportsByMentor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentors/weekly-reports/by-mentee/{menteeId}/week/{yearMonthWeek}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 멘티의 주간 리포트 목록 조회 (멘티용)
         * @description 멘티가 자신의 특정 주간 리포트 목록을 조회합니다. yearMonthWeek는 2026년 2월 1주차면 20260201 형식으로 전달
         */
        get: operations["getWeeklyReportsByMentee"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentors/weakness-solutions/by-mentor/{mentorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 멘토의 약점 솔루션 목록 조회
         * @description 멘토가 관리하는 특정 멘티의 솔루션 목록을 조회하거나, menteeId가 없으면 멘토가 등록한 모든 솔루션을 조회합니다.
         */
        get: operations["getWeaknessSolutionsByMentor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentors/qnas/{qnaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Q&A 상세 조회
         * @description 특정 Q&A의 상세 정보를 조회합니다.
         */
        get: operations["getQnaDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentors/qnas/by-mentor/{mentorId}/{userRole}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 멘토별 Q&A 목록 조회
         * @description 멘토가 답변해야 할 또는 답변한 모든 Q&A 목록을 조회합니다.
         */
        get: operations["getQnasByMentorId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentors/assignments/solutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 멘티의 솔루션 목록 조회
         * @description 특정 할일(todoId)을 통해 멘티를 식별하고, 해당 멘티의 모든 약점 솔루션과 포함된 파일명을 조회합니다.
         */
        get: operations["getMenteeSolutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedbacks/{todoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 피드백 상세 조회
         * @description 특정 할 일(Todo)에 대한 상세 정보와 작성된 피드백을 함께 조회합니다.
         */
        get: operations["getFeedbackDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedbacks/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 주간 피드백 목록 조회
         * @description 입력된 날짜가 포함된 주차의 모든 할 일과 작성된 피드백을 조회합니다.
         */
        get: operations["getWeeklyFeedbacks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedbacks/drafts/{mentorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 임시저장 피드백 목록 조회
         * @description 멘토가 작성 중인 모든 임시저장 피드백 목록을 조회합니다.
         */
        get: operations["getDraftFeedbacks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 과제 목록 조회
         * @description 전체/기간별/일별 과제 목록을 조회합니다. startDate만 있으면 일별, startDate+endDate는 기간별, 둘 다 없으면 전체 조회
         */
        get: operations["getAssignments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/{assignmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 과제 상세 조회
         * @description 과제 ID를 기반으로 상세 정보를 조회
         */
        get: operations["getAssignmentDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 주차별 과제 목록 조회
         * @description 특정 주차의 월요일 날짜를 기준으로 해당 주(월~일)의 과제 목록을 조회
         */
        get: operations["getAssignmentsWeekly"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assignments/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 학습지/파일 다운로드
         * @description 제공된 파일 URL을 통해 파일을 다운로드
         */
        get: operations["downloadFile_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/todos/drafts/{todoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 할일 임시 저장 삭제
         * @description 임시 저장된 할일을 삭제합니다.
         */
        delete: operations["deleteDraftTodo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentors/weekly-reports/{mentorId}/{reportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 주간 리포트 삭제 (비활성화)
         * @description 주간 리포트를 비활성화합니다.
         */
        delete: operations["deleteWeeklyReport"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mentors/weakness-solutions/{mentorId}/{weaknessSolutionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 약점 솔루션 삭제 (비활성화)
         * @description 약점 맞춤 솔루션을 비활성화합니다.
         */
        delete: operations["deleteWeaknessSolution"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CommonResponseVerificationResponseDto: {
            success?: boolean;
            data?: components["schemas"]["VerificationResponseDto"];
        };
        VerificationResponseDto: {
            imageUrls?: string[];
        };
        WeeklyReportUpdateRequestDto: {
            /** Format: int64 */
            reportId: number;
            /** Format: date */
            reportDate: string;
            summary: string;
            overallEvaluation: string;
            strengths: string;
            improvements: string;
        };
        CommonResponseWeeklyReportResponseDto: {
            success?: boolean;
            data?: components["schemas"]["WeeklyReportResponseDto"];
        };
        WeeklyReportResponseDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            menteeId?: number;
            /** Format: int64 */
            mentorId?: number;
            /** Format: date */
            reportDate?: string;
            summary?: string;
            overallEvaluation?: string;
            strengths?: string;
            improvements?: string;
            /** Format: date-time */
            createDatetime?: string;
            /** Format: date-time */
            updateDatetime?: string;
        };
        SolutionUpdateRequestDto: {
            /** Format: int64 */
            solutionId: number;
            subject: string;
            content: string;
        };
        CommonResponseSolutionResponseDto: {
            success?: boolean;
            data?: components["schemas"]["SolutionResponseDto"];
        };
        FileInfo: {
            fileName?: string;
            fileUrl?: string;
            description?: string;
        };
        SolutionResponseDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            menteeId?: number;
            /** Format: int64 */
            mentorId?: number;
            solutionContent?: string;
            subject?: string;
            solutionFile?: components["schemas"]["FileInfo"];
            /** Format: date-time */
            createDatetime?: string;
            /** Format: date-time */
            updateDatetime?: string;
        };
        QnaAnswerRequestDto: {
            /** Format: int64 */
            qnaId: number;
            answerContent: string;
        };
        CommonResponseQnaResponseDto: {
            success?: boolean;
            data?: components["schemas"]["QnaResponseDto"];
        };
        /** @description Q&A 응답 DTO */
        QnaResponseDto: {
            /**
             * Format: int64
             * @description Q&A ID
             * @example 1
             */
            qnaId?: number;
            /**
             * Format: int64
             * @description 멘티 ID
             * @example 2
             */
            menteeId?: number;
            /**
             * Format: int64
             * @description 멘토 ID
             * @example 1
             */
            mentorId?: number;
            /**
             * Format: date
             * @description 질문 날짜
             * @example 2026-02-09
             */
            qnaDate?: string;
            /** @description 질문 내용 */
            questionContent?: string;
            /** @description 답변 내용 */
            answerContent?: string;
            /** @description 첨부 파일 목록 */
            qnaFiles?: components["schemas"]["FileInfo"][];
            /**
             * Format: date-time
             * @description 생성 일시
             */
            createDatetime?: string;
            /**
             * Format: date-time
             * @description 수정 일시
             */
            updateDatetime?: string;
        };
        /** @description 임시 저장할 할일 정보 */
        TodoCreateRequestDto: {
            /**
             * Format: int64
             * @description 멘티 ID
             * @example 2
             */
            menteeId?: number;
            /**
             * @description 과목
             * @example KOREAN
             * @enum {string}
             */
            subject?: "KOREAN" | "ENGLISH" | "MATH";
            /**
             * @description 할일 제목
             * @example 수학 문제집 20p 풀기
             */
            title?: string;
            /**
             * @description 할일 내용
             * @example 수학의 정석 미적분 20페이지부터 25페이지까지 풀고 채점하기
             */
            content?: string;
            /**
             * Format: date
             * @description 할일 날짜 (YYYY-MM-DD)
             * @example 2026-02-08
             */
            date?: string;
            /**
             * Format: int64
             * @description 솔루션 ID
             * @example 1
             */
            solutionId?: number;
        };
        CommonResponseTodoCreateResponseDto: {
            success?: boolean;
            data?: components["schemas"]["TodoCreateResponseDto"];
        };
        TodoCreateResponseDto: {
            /** Format: int64 */
            todoId?: number;
            title?: string;
            content?: string;
            subject?: string;
            solution?: string;
            /** Format: date */
            date?: string;
            completed?: boolean;
        };
        TodoTimerSessionCreateRequestDto: {
            /**
             * Format: date-time
             * @example 2026-02-09T10:00:00
             */
            startAt?: string;
            /**
             * Format: date-time
             * @example 2026-02-09T10:25:10
             */
            endAt?: string;
        };
        CommonResponseVoid: {
            success?: boolean;
            data?: unknown;
        };
        WeeklyReportCreateRequestDto: {
            /** Format: int64 */
            menteeId: number;
            /** Format: int64 */
            mentorId: number;
            /** Format: date */
            reportDate: string;
            summary: string;
            overallEvaluation: string;
            strengths: string;
            improvements: string;
        };
        SolutionCreateRequestDto: {
            /** Format: int64 */
            menteeId: number;
            /** Format: int64 */
            mentorId: number;
            subject: string;
            content: string;
        };
        MentorAssignmentCreateRequestDto: {
            /** Format: int64 */
            menteeId?: number;
            dates?: string[];
            /** @enum {string} */
            subject?: "KOREAN" | "ENGLISH" | "MATH";
            title?: string;
            content?: string;
            /** Format: int64 */
            solutionId?: number;
            /** Format: int64 */
            goalId?: number;
            isDraft?: boolean;
        };
        LoginRequestDto: {
            /**
             * @description 사용자 이름
             * @example mentor01
             */
            id: string;
            /**
             * @description 비밀번호
             * @example 1234
             */
            password: string;
        };
        CommonResponseLoginResponseDto: {
            success?: boolean;
            data?: components["schemas"]["LoginResponseDto"];
        };
        LoginResponseDto: {
            /** Format: int64 */
            id?: number;
            role?: string;
        };
        FeedbackSaveRequestDto: {
            /** Format: int64 */
            todoId: number;
            /** Format: int64 */
            menteeId: number;
            /** Format: int64 */
            mentorId: number;
            content?: string;
            summary?: string;
        };
        CommonResponseString: {
            success?: boolean;
            data?: string;
        };
        CommonResponseListGroupedTodosResponseDto: {
            success?: boolean;
            data?: components["schemas"]["GroupedTodosResponseDto"][];
        };
        GroupedTodosResponseDto: {
            /** Format: date */
            date?: string;
            todos?: components["schemas"]["TodoListResponseDto"][];
        };
        TodoListResponseDto: {
            /** Format: int64 */
            todoId?: number;
            title?: string;
            subject?: string;
            solution?: string;
            /** Format: date */
            date?: string;
            completed?: boolean;
        };
        CommonResponseTodoDetailResponseDto: {
            success?: boolean;
            data?: components["schemas"]["TodoDetailResponseDto"];
        };
        FeedbackInfo: {
            /** Format: int64 */
            feedbackId?: number;
            content?: string;
            summary?: string;
            draftYn?: string;
            completeYn?: string;
        };
        /** @description Todo 상세 응답 DTO */
        TodoDetailResponseDto: {
            /**
             * Format: int64
             * @description 할일 ID
             * @example 1
             */
            todoId?: number;
            /**
             * @description 할일 제목
             * @example 알고리즘 문제 풀이
             */
            title?: string;
            /**
             * @description 할일 내용
             * @example 백준 1234번 문제 풀이 및 제출
             */
            content?: string;
            /**
             * @description 보완점
             * @example 첨부 파일 또는 추가 설명
             */
            solution?: string;
            /**
             * Format: date
             * @description 할일 날짜
             * @example 2024-01-01
             */
            date?: string;
            /**
             * @description 할일 과목
             * @example 수학
             */
            subject?: string;
            /**
             * @description 할일 완료 여부
             * @example true
             */
            todoCompleted?: boolean;
            /**
             * @description 피드백 작성완료 여부
             * @example false
             */
            feedbackCompleted?: boolean;
            /** @description 첨부된 학습지 파일 목록 */
            workbooks?: components["schemas"]["FileInfo"][];
            /** @description 첨부된 학습 인증 이미지 목록 */
            studyVerificationImages?: components["schemas"]["FileInfo"][];
            /** @description 할일에 대한 피드백 정보 */
            feedback?: components["schemas"]["FeedbackInfo"];
        };
        CommonResponseTodoTimerDailyResponseDto: {
            success?: boolean;
            data?: components["schemas"]["TodoTimerDailyResponseDto"];
        };
        TimerSession: {
            startAt?: string;
            endAt?: string;
            /** Format: int64 */
            minutes?: number;
        };
        TodoTimerDailyResponseDto: {
            /** Format: int64 */
            menteeId?: number;
            /** Format: date */
            date?: string;
            /** Format: int64 */
            totalMinutes?: number;
            /** Format: int64 */
            averageMinutes?: number;
            items?: components["schemas"]["TodoTimerItem"][];
        };
        TodoTimerItem: {
            /** Format: int64 */
            todoId?: number;
            title?: string;
            subject?: string;
            note?: string;
            /** Format: int64 */
            totalMinutes?: number;
            sessions?: components["schemas"]["TimerSession"][];
        };
        CommonResponseNotificationListResponseDto: {
            success?: boolean;
            data?: components["schemas"]["NotificationListResponseDto"];
        };
        NotificationDto: {
            /** Format: int64 */
            notificationId?: number;
            notificationType?: string;
            /** Format: int64 */
            dataId?: number;
            title?: string;
            content?: string;
            /** Format: date-time */
            sentAt?: string;
            read?: boolean;
        };
        NotificationListResponseDto: {
            content?: components["schemas"]["NotificationDto"][];
        };
        CommonResponseMenteeProgressResponseDto: {
            success?: boolean;
            data?: components["schemas"]["MenteeProgressResponseDto"];
        };
        MenteeProgressResponseDto: {
            /** Format: int64 */
            menteeId?: number;
            menteeName?: string;
            /** Format: double */
            overallProgress?: number;
            subjectProgressList?: components["schemas"]["SubjectProgressDto"][];
        };
        SubjectProgressDto: {
            subject?: string;
            /** Format: double */
            progress?: number;
        };
        CommonResponseMentorHomeResponseDto: {
            success?: boolean;
            data?: components["schemas"]["MentorHomeResponseDto"];
        };
        MenteeManagementDto: {
            /** Format: int64 */
            menteeId?: number;
            menteeName?: string;
            /** Format: int32 */
            completedCount?: number;
            /** Format: int32 */
            totalCount?: number;
            unsubmittedTitles?: string[];
            /** Format: double */
            progressRate?: number;
        };
        MentorAssignmentSummaryDto: {
            /** Format: int64 */
            assignmentId?: number;
            /** Format: int64 */
            menteeId?: number;
            menteeName?: string;
            title?: string;
            /** Format: date */
            todoDate?: string;
            status?: string;
        };
        MentorFeedbackSummaryDto: {
            /** Format: int64 */
            feedbackId?: number;
            /** Format: int64 */
            menteeId?: number;
            menteeName?: string;
            /** Format: int64 */
            todoId?: number;
            /** Format: date */
            feedDate?: string;
            status?: string;
        };
        MentorHomeResponseDto: {
            assignments?: components["schemas"]["MentorAssignmentSummaryDto"][];
            feedbacks?: components["schemas"]["MentorFeedbackSummaryDto"][];
            qnas?: components["schemas"]["MentorQnaSummaryDto"][];
            menteeManagement?: components["schemas"]["MenteeManagementDto"][];
        };
        MentorQnaSummaryDto: {
            /** Format: int64 */
            qnaId?: number;
            /** Format: int64 */
            menteeId?: number;
            menteeName?: string;
            status?: string;
            /** Format: date-time */
            createDatetime?: string;
        };
        CommonResponseDraftCountResponseDto: {
            success?: boolean;
            data?: components["schemas"]["DraftCountResponseDto"];
        };
        /** @description 임시저장 개수 정보 */
        DraftCountResponseDto: {
            /**
             * Format: int64
             * @description 과제 임시저장 개수
             */
            assignmentDraftCount?: number;
            /**
             * Format: int64
             * @description 피드백 임시저장 개수
             */
            feedbackDraftCount?: number;
            /**
             * Format: int64
             * @description 전체 임시저장 개수 합계
             */
            totalDraftCount?: number;
        };
        CommonResponseListWeeklyReportResponseDto: {
            success?: boolean;
            data?: components["schemas"]["WeeklyReportResponseDto"][];
        };
        CommonResponseWeeklyMenteeReportResponseDto: {
            success?: boolean;
            data?: components["schemas"]["WeeklyMenteeReportResponseDto"];
        };
        WeeklyMenteeReportResponseDto: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            mentorId?: number;
            /** Format: date */
            reportDate?: string;
            summary?: string;
            overallEvaluation?: string;
            strengths?: string;
            improvements?: string;
            /** Format: date-time */
            createDatetime?: string;
            /** Format: date-time */
            updateDatetime?: string;
            /** Format: int32 */
            assignmentPercent?: number;
            /** Format: int32 */
            todoPercent?: number;
            subjectPercents?: {
                [key: string]: number;
            };
        };
        CommonResponseListSolutionResponseDto: {
            success?: boolean;
            data?: components["schemas"]["SolutionResponseDto"][];
        };
        CommonResponseListQnaResponseDto: {
            success?: boolean;
            data?: components["schemas"]["QnaResponseDto"][];
        };
        CommonResponseListMentorSolutionResponseDto: {
            success?: boolean;
            data?: components["schemas"]["MentorSolutionResponseDto"][];
        };
        MentorSolutionResponseDto: {
            /** Format: int64 */
            solutionId?: number;
            solutionContent?: string;
            fileName?: string;
            fileUrl?: string;
        };
        CommonResponseFeedbackDetailResponseDto: {
            success?: boolean;
            data?: components["schemas"]["FeedbackDetailResponseDto"];
        };
        FeedbackDetailResponseDto: {
            /** Format: int64 */
            todoId?: number;
            todoName?: string;
            todoNote?: string;
            todoSubjects?: string;
            /** Format: date */
            todoDate?: string;
            verificationImages?: string[];
            feedback?: components["schemas"]["FeedbackInfo"];
        };
        CommonResponseFeedbackWeeklyResponseDto: {
            success?: boolean;
            data?: components["schemas"]["FeedbackWeeklyResponseDto"];
        };
        FeedbackDetailDto: {
            /** Format: int64 */
            feedbackId?: number;
            content?: string;
            summary?: string;
            draftYn?: string;
            completeYn?: string;
        };
        FeedbackWeeklyResponseDto: {
            weekInfo?: string;
            /** Format: date */
            mondayDate?: string;
            groupedItems?: {
                [key: string]: components["schemas"]["TodoWithFeedbackDto"][];
            };
        };
        TodoWithFeedbackDto: {
            /** Format: int64 */
            todoId?: number;
            /** Format: int64 */
            menteeId?: number;
            menteeName?: string;
            todoName?: string;
            todoNote?: string;
            todoSubjects?: string;
            todoCompleteYn?: string;
            todoAssignYn?: string;
            /** Format: date */
            todoDate?: string;
            verificationImages?: string[];
            feedback?: components["schemas"]["FeedbackDetailDto"];
        };
        CommonResponseListTodoWithFeedbackDto: {
            success?: boolean;
            data?: components["schemas"]["TodoWithFeedbackDto"][];
        };
        AssignmentListResponseDto: {
            /** Format: int64 */
            assignmentId?: number;
            title?: string;
            subject?: string;
            solution?: string;
            /** Format: date */
            date?: string;
            completed?: boolean;
        };
        CommonResponseListGroupedAssignmentsResponseDto: {
            success?: boolean;
            data?: components["schemas"]["GroupedAssignmentsResponseDto"][];
        };
        GroupedAssignmentsResponseDto: {
            /** Format: date */
            date?: string;
            assignments?: components["schemas"]["AssignmentListResponseDto"][];
        };
        /** @description 과제 상세 응답 DTO */
        AssignmentDetailResponseDto: {
            /**
             * Format: int64
             * @description 과제 ID
             * @example 1
             */
            assignmentId?: number;
            /**
             * @description 과제 제목
             * @example Spring Boot 과제
             */
            title?: string;
            /**
             * @description 과제 내용
             * @example 게시판 CRUD 구현하기
             */
            content?: string;
            /**
             * @description 보완점
             * @example 첨부 파일 또는 추가 설명
             */
            solution?: string;
            /**
             * Format: date
             * @description 과제 날짜
             * @example 2024-01-01
             */
            date?: string;
            /**
             * @description 과제 과목
             * @example 백엔드
             */
            subject?: string;
            /**
             * @description 과제 완료 여부
             * @example true
             */
            assignmentCompleted?: boolean;
            /**
             * @description 피드백 작성완료 여부
             * @example false
             */
            feedbackCompleted?: boolean;
            /** @description 첨부된 학습지 파일 목록 */
            workbooks?: components["schemas"]["FileInfo"][];
            /** @description 첨부된 학습 인증 이미지 목록 */
            studyVerificationImages?: components["schemas"]["FileInfo"][];
            /** @description 과제에 대한 피드백 정보 */
            feedback?: components["schemas"]["FeedbackInfo"];
        };
        CommonResponseAssignmentDetailResponseDto: {
            success?: boolean;
            data?: components["schemas"]["AssignmentDetailResponseDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    updateVerification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 할일 ID
                 * @example 1
                 */
                todoId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** @description 새로운 인증 사진 파일 (여러 개 가능) */
                    images: string[];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseVerificationResponseDto"];
                };
            };
        };
    };
    uploadVerification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 할일 ID
                 * @example 1
                 */
                todoId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** @description 인증 사진 파일 (여러 개 가능) */
                    images: string[];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseVerificationResponseDto"];
                };
            };
        };
    };
    deleteVerification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 할일 ID
                 * @example 1
                 */
                todoId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseVerificationResponseDto"];
                };
            };
        };
    };
    updateWeeklyReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mentorId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeeklyReportUpdateRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseWeeklyReportResponseDto"];
                };
            };
        };
    };
    createWeeklyReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mentorId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeeklyReportCreateRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseWeeklyReportResponseDto"];
                };
            };
        };
    };
    updateWeaknessSolution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mentorId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    request: components["schemas"]["SolutionUpdateRequestDto"];
                    /** Format: binary */
                    files?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseSolutionResponseDto"];
                };
            };
        };
    };
    createWeaknessSolution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mentorId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    request: components["schemas"]["SolutionCreateRequestDto"];
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseSolutionResponseDto"];
                };
            };
        };
    };
    answerQna: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
                userRole: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QnaAnswerRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseQnaResponseDto"];
                };
            };
        };
    };
    getQna: {
        parameters: {
            query: {
                /**
                 * @description 멘티 ID
                 * @example 2
                 */
                menteeId: number;
                /**
                 * @description 조회 날짜 (YYYY-MM-DD)
                 * @example 2026-02-09
                 */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseQnaResponseDto"];
                };
            };
        };
    };
    updateQna: {
        parameters: {
            query: {
                /**
                 * @description Q&A ID
                 * @example 1
                 */
                qnaId: number;
                /**
                 * @description 질문 내용
                 * @example 수정된 질문 내용입니다.
                 */
                questionContent?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** @description 첨부 파일 (여러 개 가능) */
                    files?: string[];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseQnaResponseDto"];
                };
            };
        };
    };
    createQna: {
        parameters: {
            query: {
                /**
                 * @description 멘티 ID
                 * @example 2
                 */
                menteeId: number;
                /**
                 * @description 질문 내용
                 * @example 이 문제 풀이 방법을 알려주세요.
                 */
                questionContent: string;
                /**
                 * @description 질문 날짜 (YYYY-MM-DD)
                 * @example 2026-02-09
                 */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** @description 첨부 파일 (여러 개 가능) */
                    files?: string[];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseQnaResponseDto"];
                };
            };
        };
    };
    deleteQna: {
        parameters: {
            query: {
                /**
                 * @description Q&A ID
                 * @example 1
                 */
                qnaId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseVoid"];
                };
            };
        };
    };
    updateVerification_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 과제 ID
                 * @example 1
                 */
                assignmentId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** @description 새로운 인증 사진 파일 (여러 개 가능) */
                    images: string[];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseVerificationResponseDto"];
                };
            };
        };
    };
    uploadVerification_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 과제 ID
                 * @example 1
                 */
                assignmentId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** @description 인증 사진 파일 (여러 개 가능) */
                    images: string[];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseVerificationResponseDto"];
                };
            };
        };
    };
    deleteVerification_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 과제 ID
                 * @example 1
                 */
                assignmentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseVerificationResponseDto"];
                };
            };
        };
    };
    getTodos: {
        parameters: {
            query: {
                /**
                 * @description 멘티 ID
                 * @example 2
                 */
                menteeId: number;
                /**
                 * @description 시작 날짜 (YYYY-MM-DD), startDate만 있으면 일별, startDate+endDate는 기간별, 둘 다 없으면 전체 조회
                 * @example 2026-02-01
                 */
                startDate?: string;
                /**
                 * @description 종료 날짜 (YYYY-MM-DD)
                 * @example 2026-02-20
                 */
                endDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseListGroupedTodosResponseDto"];
                };
            };
        };
    };
    createTodo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TodoCreateRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseTodoCreateResponseDto"];
                };
            };
        };
    };
    addTimerSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                todoId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TodoTimerSessionCreateRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseVoid"];
                };
            };
        };
    };
    getDraftTodos: {
        parameters: {
            query: {
                /**
                 * @description 멘티 ID
                 * @example 2
                 */
                menteeId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseListGroupedTodosResponseDto"];
                };
            };
        };
    };
    createDraftTodo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TodoCreateRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseTodoCreateResponseDto"];
                };
            };
        };
    };
    createAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    request: components["schemas"]["MentorAssignmentCreateRequestDto"];
                    workbooks?: string[];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseLoginResponseDto"];
                };
            };
        };
    };
    saveFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackSaveRequestDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseVoid"];
                };
            };
        };
    };
    triggerImageAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                todoId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseString"];
                };
            };
        };
    };
    toggleStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 할일 ID
                 * @example 1
                 */
                todoId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseVoid"];
                };
            };
        };
    };
    getTodoDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 할일 ID
                 * @example 1
                 */
                todoId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseTodoDetailResponseDto"];
                };
            };
        };
    };
    getTodosWeekly: {
        parameters: {
            query: {
                /**
                 * @description 멘티 ID
                 * @example 2
                 */
                menteeId: number;
                /**
                 * @description 주차의 월요일 날짜 (YYYY-MM-DD)
                 * @example 2026-02-02
                 */
                mondayDate: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseListGroupedTodosResponseDto"];
                };
            };
        };
    };
    getTimersByDate: {
        parameters: {
            query: {
                /**
                 * @description 멘티 ID
                 * @example 2
                 */
                menteeId: number;
                /**
                 * @description 조회할 날짜 (YYYY-MM-DD)
                 * @example 2026-02-03
                 */
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseTodoTimerDailyResponseDto"];
                };
            };
        };
    };
    downloadFile: {
        parameters: {
            query: {
                /** @description 파일 URL (예: /solutions/국어/1/file1.pdf) */
                fileUrl: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    getNotifications: {
        parameters: {
            query: {
                menteeId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseNotificationListResponseDto"];
                };
            };
        };
    };
    getMenteeProgress: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mentorId: number;
                menteeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseMenteeProgressResponseDto"];
                };
            };
        };
    };
    getMentorHomeData: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path: {
                mentorId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseMentorHomeResponseDto"];
                };
            };
        };
    };
    getDraftCounts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mentorId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseDraftCountResponseDto"];
                };
            };
        };
    };
    getWeeklyReportDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseWeeklyReportResponseDto"];
                };
            };
        };
    };
    getWeeklyReportsByMentor: {
        parameters: {
            query: {
                mondayDate: string;
            };
            header?: never;
            path: {
                mentorId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseListWeeklyReportResponseDto"];
                };
            };
        };
    };
    getWeeklyReportsByMentee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                menteeId: number;
                yearMonthWeek: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseWeeklyMenteeReportResponseDto"];
                };
            };
        };
    };
    getWeaknessSolutionsByMentor: {
        parameters: {
            query?: {
                menteeId?: number;
            };
            header?: never;
            path: {
                mentorId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseListSolutionResponseDto"];
                };
            };
        };
    };
    getQnaDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                qnaId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseQnaResponseDto"];
                };
            };
        };
    };
    getQnasByMentorId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mentorId: number;
                userRole: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseListQnaResponseDto"];
                };
            };
        };
    };
    getMenteeSolutions: {
        parameters: {
            query: {
                /**
                 * @description 할일 ID
                 * @example 1
                 */
                todoId: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseListMentorSolutionResponseDto"];
                };
            };
        };
    };
    getFeedbackDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                todoId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseFeedbackDetailResponseDto"];
                };
            };
        };
    };
    getWeeklyFeedbacks: {
        parameters: {
            query: {
                mentorId: number;
                menteeId?: number;
                type?: string;
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseFeedbackWeeklyResponseDto"];
                };
            };
        };
    };
    getDraftFeedbacks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mentorId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseListTodoWithFeedbackDto"];
                };
            };
        };
    };
    getAssignments: {
        parameters: {
            query: {
                /**
                 * @description 멘티 ID
                 * @example 2
                 */
                menteeId: number;
                /**
                 * @description 시작 날짜 (YYYY-MM-DD), startDate만 있으면 일별, startDate+endDate는 기간별, 둘 다 없으면 전체 조회
                 * @example 2026-02-01
                 */
                startDate?: string;
                /**
                 * @description 종료 날짜 (YYYY-MM-DD)
                 * @example 2026-02-20
                 */
                endDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseListGroupedAssignmentsResponseDto"];
                };
            };
        };
    };
    getAssignmentDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 과제 ID
                 * @example 1
                 */
                assignmentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseAssignmentDetailResponseDto"];
                };
            };
        };
    };
    getAssignmentsWeekly: {
        parameters: {
            query: {
                /**
                 * @description 멘티 ID
                 * @example 2
                 */
                menteeId?: number;
                /**
                 * @description 주차의 월요일 날짜 (YYYY-MM-DD)
                 * @example 2026-02-02
                 */
                mondayDate: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseListGroupedAssignmentsResponseDto"];
                };
            };
        };
    };
    downloadFile_1: {
        parameters: {
            query: {
                /** @description 파일 URL (예: /solutions/국어/1/file1.pdf) */
                fileUrl: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    deleteDraftTodo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description 할일 ID
                 * @example 1
                 */
                todoId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseVoid"];
                };
            };
        };
    };
    deleteWeeklyReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mentorId: number;
                reportId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseVoid"];
                };
            };
        };
    };
    deleteWeaknessSolution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mentorId: number;
                weaknessSolutionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommonResponseVoid"];
                };
            };
        };
    };
}
